version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - "type: dependencies"
      - "status: needs-review"
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - "type: dependencies"
      - "status: needs-review"
    open-pull-requests-limit: 5
